/* ============================================================
   build-states.mjs — generate src/data/state-shapes.ts
   --------------------------------------------------------------
   Fetches a low-res US-states GeoJSON, keeps only the eight
   states the roadtrip crosses, maps each to its USPS code, and
   writes the polygon rings as plain data. Generated file — do
   not hand-edit src/data/state-shapes.ts; re-run this instead:

     node scripts/build-states.mjs

   Same offline-safe rationale as the stadium/flag assets: we
   bake the geometry into the repo rather than fetch at runtime.
   ============================================================ */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC =
  "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json";

// Full GeoJSON name → USPS code, in trip order (west → east).
const WANT = {
  California: "CA",
  Nevada: "NV",
  Arizona: "AZ",
  "New Mexico": "NM",
  Texas: "TX",
  Oklahoma: "OK",
  Kansas: "KS",
  Missouri: "MO",
};

const res = await fetch(SRC);
if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
const fc = await res.json();

// Round coords to 4 decimals (~11 m) to keep the file small.
const r = (n) => Math.round(n * 1e4) / 1e4;

const out = [];
for (const [name, code] of Object.entries(WANT)) {
  const feat = fc.features.find((f) => f.properties.name === name);
  if (!feat) throw new Error(`missing state in source: ${name}`);
  const g = feat.geometry;
  // Normalise Polygon → MultiPolygon-style list of rings (lat,lon tuples).
  const polys =
    g.type === "Polygon" ? [g.coordinates] : g.coordinates; // MultiPolygon
  // Each ring: [lon,lat] in GeoJSON → [lat,lon] for Leaflet.
  const rings = polys.map((poly) =>
    poly.map((ring) => ring.map(([lon, lat]) => [r(lat), r(lon)]))
  );
  out.push({ code, name, rings });
}

const header = `/* US state outlines for the eight states the roadtrip crosses.
   GENERATED by scripts/build-states.mjs — do not hand-edit.
   Rings are [lat, lon] tuples (Leaflet order). A state may have
   several polygons (each an outer ring; no holes in this data). */

import type { Coords } from "./trip.types";

export interface StateShape {
  /** USPS code, e.g. "CA". */
  code: string;
  /** GeoJSON full name, e.g. "California". */
  name: string;
  /** One or more polygons, each a list of [lat, lon] rings. */
  rings: Coords[][][];
}

export const STATE_SHAPES: StateShape[] = `;

const body = JSON.stringify(out);
writeFileSync(
  join(__dirname, "..", "src", "data", "state-shapes.ts"),
  `${header}${body};\n`
);

const bytes = Buffer.byteLength(body);
console.log(`wrote ${out.length} states, ${(bytes / 1024).toFixed(1)} KB geometry`);
