/* ------------------------------------------------------------------
   Embed curated road-trip photos onto the map.
   - reads EXIF GPS + capture time (shared reader)
   - resizes with sharp into public/photos/ (metadata stripped)
   - upserts scripts/photos.manifest.json (captions preserved)
   - regenerates src/data/photos.ts
   Usage: node scripts/process-photos.mjs <filenameToken> [<token> ...]
   Tokens may omit the .jpg suffix; resolved by prefix match.
   ------------------------------------------------------------------ */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { readEXIF } from "./exif-reader.mjs";

const PHOTO_DIR = process.env.PHOTO_DIR || "C:\\Users\\KlausLehner\\Pictures\\USA-Roadtrip";
const PUBLIC_DIR = join(import.meta.dirname, "..", "public", "photos");
const MANIFEST = join(import.meta.dirname, "photos.manifest.json");
const OUT_TS = join(import.meta.dirname, "..", "src", "data", "photos.ts");

const round6 = (n) => Math.round(n * 1e6) / 1e6;

function resolveFile(token, files) {
  if (files.includes(token)) return token;
  return files.find((f) => /\.jpe?g$/i.test(f) && f.startsWith(token)) || null;
}
function idFromName(f) {
  const m = f.match(/(\d{8})_(\d{6})/);
  return m ? `p-${m[1]}-${m[2]}` : f.replace(/\.[^.]+$/, "").toLowerCase();
}
function isoTime(exifDate, file) {
  const m = exifDate && exifDate.match(/(\d{4}):(\d{2}):(\d{2})\s+(\d{2}):(\d{2}):(\d{2})/);
  if (m) return `${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}`;
  const f = file.match(/(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2})/);
  return f ? `${f[1]}-${f[2]}-${f[3]}T${f[4]}:${f[5]}:${f[6]}` : null;
}

const tokens = process.argv.slice(2);
if (!tokens.length) {
  console.error("usage: node scripts/process-photos.mjs <filenameToken> [<token> ...]");
  process.exit(1);
}

mkdirSync(PUBLIC_DIR, { recursive: true });
const files = readdirSync(PHOTO_DIR);

let manifest = existsSync(MANIFEST) ? JSON.parse(readFileSync(MANIFEST, "utf8")) : [];
const byId = new Map(manifest.map((e) => [e.id, e]));

for (const token of tokens) {
  const file = resolveFile(token, files);
  if (!file) { console.warn(`! no file for token: ${token}`); continue; }
  const buf = readFileSync(join(PHOTO_DIR, file));
  let exif = null;
  try { exif = readEXIF(buf); } catch { exif = null; }
  const id = idFromName(file);
  const coords = exif && exif.lat != null ? [round6(exif.lat), round6(exif.lon)] : null;
  if (!coords) console.warn(`! no GPS: ${file} (recorded with coords:null, skipped from map)`);
  const time = isoTime(exif?.dateTime, file);

  // Full image (rotate bakes orientation; metadata stripped by default).
  const { data, info } = await sharp(buf, { failOn: "none" })
    .rotate()
    .resize(1600, 1600, { fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 82 })
    .toBuffer({ resolveWithObject: true });
  writeFileSync(join(PUBLIC_DIR, `${id}.jpg`), data);
  await sharp(buf, { failOn: "none" })
    .rotate()
    .resize(200, 200, { fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 70 })
    .toFile(join(PUBLIC_DIR, `${id}-thumb.jpg`));

  const prev = byId.get(id);
  byId.set(id, {
    id,
    file,
    coords,
    time,
    thumb: `/photos/${id}-thumb.jpg`,
    full: `/photos/${id}.jpg`,
    w: info.width,
    h: info.height,
    caption: prev?.caption ?? "",
  });
  console.log(`✓ ${file} -> ${id} ${coords ? coords.join(",") : "(no gps)"}`);
}

const merged = [...byId.values()].sort((a, b) => (a.time || "").localeCompare(b.time || ""));
writeFileSync(MANIFEST, JSON.stringify(merged, null, 2) + "\n");

const placed = merged.filter((e) => e.coords);
const rows = placed
  .map((e) => {
    const cap = e.caption ? `, caption: ${JSON.stringify(e.caption)}` : "";
    return `  { id: ${JSON.stringify(e.id)}, coords: [${e.coords[0]}, ${e.coords[1]}], time: ${JSON.stringify(e.time)}, thumb: ${JSON.stringify(e.thumb)}, full: ${JSON.stringify(e.full)}, w: ${e.w}, h: ${e.h}${cap} },`;
  })
  .join("\n");
writeFileSync(
  OUT_TS,
  `// GENERATED by scripts/process-photos.mjs — do not hand-edit.\n` +
    `// Captions are edited in scripts/photos.manifest.json, then regenerate.\n` +
    `import type { TripPhoto } from "./trip.types";\n\n` +
    `export const PHOTOS: TripPhoto[] = [\n${rows}\n];\n`
);
console.log(`\nphotos.ts: ${placed.length} placed, manifest: ${merged.length} total`);
