// GENERATED by scripts/process-photos.mjs — do not hand-edit.
// Captions are edited in scripts/photos.manifest.json, then regenerate.
import type { TripPhoto } from "./trip.types";

export const PHOTOS: TripPhoto[] = [
  { id: "p-20260613-160124", coords: [37.763461, -122.509831], time: "2026-06-13T09:01:24", thumb: "/photos/p-20260613-160124-thumb.jpg", full: "/photos/p-20260613-160124.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-180353", coords: [37.779556, -122.416939], time: "2026-06-13T11:03:53", thumb: "/photos/p-20260613-180353-thumb.jpg", full: "/photos/p-20260613-180353.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-190308", coords: [37.787281, -122.408247], time: "2026-06-13T12:03:08", thumb: "/photos/p-20260613-190308-thumb.jpg", full: "/photos/p-20260613-190308.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-200659", coords: [37.808106, -122.421056], time: "2026-06-13T13:06:59", thumb: "/photos/p-20260613-200659-thumb.jpg", full: "/photos/p-20260613-200659.jpg", w: 1600, h: 1205 },
];
