// GENERATED by scripts/process-photos.mjs — do not hand-edit.
// Captions are edited in scripts/photos.manifest.json, then regenerate.
import type { TripPhoto } from "./trip.types";

export const PHOTOS: TripPhoto[] = [
  { id: "p-20260613-160124", coords: [37.763461, -122.509831], time: "2026-06-13T09:01:24", thumb: "/photos/p-20260613-160124-thumb.jpg", full: "/photos/p-20260613-160124.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-180353", coords: [37.779556, -122.416939], time: "2026-06-13T11:03:53", thumb: "/photos/p-20260613-180353-thumb.jpg", full: "/photos/p-20260613-180353.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-190308", coords: [37.787281, -122.408247], time: "2026-06-13T12:03:08", thumb: "/photos/p-20260613-190308-thumb.jpg", full: "/photos/p-20260613-190308.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-200659", coords: [37.808106, -122.421056], time: "2026-06-13T13:06:59", thumb: "/photos/p-20260613-200659-thumb.jpg", full: "/photos/p-20260613-200659.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-210129", coords: [37.803, -122.411778], time: "2026-06-13T14:01:29", thumb: "/photos/p-20260613-210129-thumb.jpg", full: "/photos/p-20260613-210129.jpg", w: 1600, h: 1205 },
  { id: "p-20260613-215940", coords: [37.802183, -122.418019], time: "2026-06-13T14:59:40", thumb: "/photos/p-20260613-215940-thumb.jpg", full: "/photos/p-20260613-215940.jpg", w: 1205, h: 1600 },
  { id: "p-20260613-220305", coords: [37.802178, -122.418286], time: "2026-06-13T15:03:05", thumb: "/photos/p-20260613-220305-thumb.jpg", full: "/photos/p-20260613-220305.jpg", w: 1205, h: 1600 },
  { id: "p-20260613-220955", coords: [37.802064, -122.419597], time: "2026-06-13T15:09:55", thumb: "/photos/p-20260613-220955-thumb.jpg", full: "/photos/p-20260613-220955.jpg", w: 1205, h: 1600 },
  { id: "p-20260613-223642", coords: [37.793522, -122.407342], time: "2026-06-13T15:36:42", thumb: "/photos/p-20260613-223642-thumb.jpg", full: "/photos/p-20260613-223642.jpg", w: 1205, h: 1600 },
  { id: "p-20260614-001703", coords: [37.796667, -122.394933], time: "2026-06-13T17:17:03", thumb: "/photos/p-20260614-001703-thumb.jpg", full: "/photos/p-20260614-001703.jpg", w: 1600, h: 1205 },
  { id: "p-20260614-044059", coords: [37.776758, -122.419528], time: "2026-06-13T21:40:59", thumb: "/photos/p-20260614-044059-thumb.jpg", full: "/photos/p-20260614-044059.jpg", w: 1205, h: 1600 },
  { id: "p-20260614-050704", coords: [37.763122, -122.5097], time: "2026-06-13T22:07:04", thumb: "/photos/p-20260614-050704-thumb.jpg", full: "/photos/p-20260614-050704.jpg", w: 1600, h: 1205 },
  { id: "p-20260614-174828", coords: [37.790458, -122.390469], time: "2026-06-14T10:48:28", thumb: "/photos/p-20260614-174828-thumb.jpg", full: "/photos/p-20260614-174828.jpg", w: 1600, h: 1205 },
  { id: "p-20260614-190758", coords: [37.814331, -122.405183], time: "2026-06-14T12:07:58", thumb: "/photos/p-20260614-190758-thumb.jpg", full: "/photos/p-20260614-190758.jpg", w: 1205, h: 1600 },
  { id: "p-20260614-191443", coords: [37.827533, -122.418519], time: "2026-06-14T12:14:43", thumb: "/photos/p-20260614-191443-thumb.jpg", full: "/photos/p-20260614-191443.jpg", w: 1600, h: 1205 },
  { id: "p-20260614-195341", coords: [37.826525, -122.422639], time: "2026-06-14T12:53:41", thumb: "/photos/p-20260614-195341-thumb.jpg", full: "/photos/p-20260614-195341.jpg", w: 1205, h: 1600 },
  { id: "p-20260614-195446", coords: [37.82675, -122.422767], time: "2026-06-14T12:54:46", thumb: "/photos/p-20260614-195446-thumb.jpg", full: "/photos/p-20260614-195446.jpg", w: 1600, h: 1205 },
  { id: "p-20260614-200425", coords: [37.826872, -122.422939], time: "2026-06-14T13:04:25", thumb: "/photos/p-20260614-200425-thumb.jpg", full: "/photos/p-20260614-200425.jpg", w: 1205, h: 1600 },
  { id: "p-20260614-204203", coords: [37.826178, -122.422275], time: "2026-06-14T13:42:03", thumb: "/photos/p-20260614-204203-thumb.jpg", full: "/photos/p-20260614-204203.jpg", w: 1600, h: 1205 },
];
